
CREATE DATABASE IF NOT EXISTS MYDB;

USE MYDB;

DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER
(
 USER_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(30),
 PASSWORD VARCHAR(30)
);

DROP TABLE IF EXISTS TBL_ORGANISATION;

CREATE TABLE TBL_ORGANISATION
(
 ORG_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(30),
 CODE VARCHAR(30)
);

DROP TABLE IF EXISTS TBL_ROLE;

CREATE TABLE TBL_ROLE
(
 ROLE_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(30),
 CODE VARCHAR(30)
);

INSERT INTO TBL_USER(EMAIL,PASSWORD) VALUES('abc@gmail.com','password1');

SELECT * FROM TBL_USER;
