
CREATE USER 'monty'@'localhost' IDENTIFIED BY 'some_pass';
GRANT ALL PRIVILEGES ON *.* TO 'monty'@'localhost' WITH GRANT OPTION;
CREATE USER 'monty'@'%' IDENTIFIED BY 'some_pass';
GRANT ALL PRIVILEGES ON *.* TO 'monty'@'%' WITH GRANT OPTION;

CREATE USER 'root'@'%' IDENTIFIED BY 'password1';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' identified by 'password1';

CREATE USER 'admin'@'localhost';
GRANT RELOAD,PROCESS ON *.* TO 'admin'@'localhost';
CREATE USER 'dummy'@'localhost';
FLUSH PRIVILEGES;

select User,Host from mysql.user;

CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER
(
 USER_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(30),
 PASSWORD VARCHAR(30)
);

DROP TABLE IF EXISTS TBL_ORGANISATION;

CREATE TABLE TBL_ORGANISATION
(
 ORG_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(30),
 CODE VARCHAR(30)
);

DROP TABLE IF EXISTS TBL_ROLE;

CREATE TABLE TBL_ROLE
(
 ROLE_ID INT(6) AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(30),
 CODE VARCHAR(30)
);

INSERT INTO TBL_USER(EMAIL,PASSWORD) VALUES('abc@gmail.com','password1');

SELECT * FROM TBL_USER;
